### ISSUE TITLE
AUTO CAD software at Dahej Workshop

### ISSUE THREAD

**Issue by praveen-isgec** [Isgec/ITIL-CMDB#16]
Autocad Application required for Dahej Workshop.

We are using autocad 2016 at dahej workshop, which license has expired, So please do the needful to activate Autocad.
 
Regards,
Manjeet Singh
Dahej Workshop

@Isgec/dc-infra-team ,  Myself Praveen Kumar is working for the same.

**Comment by vinay-isgec** [comment]
Hi Team,

 

Please install Autocad 2020 in Mr. Chetan’s system at Dahej Workshop. Autodesk account details as follows.

 

Autodesk Account:                         chetan.patel@isgec.co.in 

 

 

If you have any additional questions or concerns you would like us to address, or require any further assistance, please let us know.

Regards.....

Praveen (SYSTEMS)

cid:image002.png@01D5CC89.FCA7D120

A-8, Sector- 63, Noida, UP

Email: praveen1.kumar@isgec.co.in

website: www.isgec.com

Mobile:  +91 8448595785

 

From: Vinay Sharma [mailto:vinay.sharma@isgec.co.in] 
Sent: 02 February 2021 16:15
To: praveen1.kumar@isgec.co.in
Subject: FW: Activation of AUTO CAD software at Dahej Workshop

 

fyi

 

From: PPC ISGECDAHEJ [mailto:ppc.isgecdahejepc@gmail.com] 
Sent: 02 February 2021 16:09
To: Vinay Sharma
Subject: Fwd: Activation of AUTO CAD software at Dahej Workshop

 

Dear Vinay Sir,

 

In reference to trailing mail, please find the employee details as discussed.

 

Mail Id:- chetan.patel@isgec.co.in

Emp. Id:- 3640

 

 

Regards,

Manjeet Singh

 

---------- Forwarded message ---------
From: Harish Kaushik <harish.kaushik@isgec.co.in>
Date: Tue, Feb 2, 2021 at 3:42 PM
Subject: RE: Activation of AUTO CAD software at Dahej Workshop
To: Vinay Sharma <vinay.sharma@isgec.co.in>
Cc: PPC ISGECDAHEJ <ppc.isgecdahejepc@gmail.com>, vinay sharma <vinay.sharma@isgec.co.in>, Chetan Patel <chetan.patel@isgec.co.in>, Sanjiv Kumar <sanjiv6dgp@gmail.com>, Yatish Singh <yatish.singh@isgec.co.in>, ESG Pragasam <esgpragasam@isgec.co.in>

 

Dear Sir,

 

As discussed, please do the needful.

 

Thanks & Regards,

Harish Kaushik

 

From: Yatish Singh <yatish.singh@isgec.co.in> 
Sent: 02 February 2021 15:39
To: harish.kaushik@isgec.co.in
Cc: 'PPC ISGECDAHEJ' <ppc.isgecdahejepc@gmail.com>; 'vinay sharma' <vinay.sharma@isgec.co.in>; 'Chetan Patel' <chetan.patel@isgec.co.in>; 'Sanjiv Kumar' <sanjiv6dgp@gmail.com>
Subject: RE: Activation of AUTO CAD software at Dahej Workshop

 

Dear Sir,

 

Please update the AUTO CAD software on the Mr. Manjeet & Mr. Chetan computer systems working at Dahej (Works).

 

Copy of MD sanction is attached herewith for your reference.

 

Regards

 

Yatish Chand Singh (3484)

Manager Construction- EPC Projects 

Description: Isgec eSign

A-4, Sec-24, Noida - 201301 (UP)

Ph: +91 120 408 5199 (Direct)

Mob: +91- 7303188022, 9812509126

Email: yatish.singh@isgec.co.in

website:  <http://www.isgec.com/> www.isgec.com

 

 

From: Sanjiv Kumar [mailto:sanjiv6dgp@gmail.com] 
Sent: 02 February 2021 15:23
To: Yatish Chand Singh
Cc: PPC ISGECDAHEJ; vinay sharma; Chetan Patel
Subject: Fwd: FW: Dahej Workshop: AutoCad Activation required

 

Dear Yatish,

 

Refer the trailing mail & do the needful as because Auto cad is required at our workshop.

 

 

Thanks & Regards,

Sanjiv Kumar (ESJ)

ISGEC EPC DAHEJ

Mob - 7988304181

 

 

---------- Forwarded message ---------
From: PPC ISGECDAHEJ <ppc.isgecdahejepc@gmail.com>
Date: Tue, Feb 2, 2021 at 2:52 PM
Subject: Re: FW: Dahej Workshop: AutoCad Activation required
To: Vinay Sharma <vinay.sharma@isgec.co.in>
Cc: Sanjiv Kumar <sanjiv6dgp@gmail.com>

 

Dear Sir,

 

Auto cad required for drafting and converting drawing file for CNC Nesting/Cutting program.

 

 

Regards,

Manjeet Singh 

 

On Tue, Feb 2, 2021 at 2:32 PM Vinay Sharma <vinay.sharma@isgec.co.in> wrote:

Dear Manjeet,

 Please see the trail mail reply on it about the requirement of AutoCAD.

 Regards

Vinay 

 From: Harish Kaushik [mailto:harish.kaushik@isgec.co.in] 
Sent: 02 February 2021 14:29
To: 'Vinay Sharma'
Cc: dhirendra.singh@isgec.co.in; praveen1.kumar@isgec.co.in; 'ESG Pragasam'
Subject: RE: Dahej Workshop: AutoCad Activation required

 Dear Sir,

 Can you please ask them ‘Why they required AutoCAD at Site.’

 Thanks & Regards,

Harish Kaushik

From: Vinay Sharma <vinay.sharma@isgec.co.in> 
Sent: 02 February 2021 14:22
To: harish.kaushik@isgec.co.in
Cc: dhirendra.singh@isgec.co.in; praveen1.kumar@isgec.co.in
Subject: FW: Dahej Workshop: AutoCad Activation required

 Dear harish,

 Kindly provide KV approval for AutoCAD  Dahej site user 

Regards

Vinay 

 From: PPC ISGECDAHEJ [mailto:ppc.isgecdahejepc@gmail.com] 
Sent: 02 February 2021 11:35
To: vinay.sharma@isgec.co.in
Cc: Sanjiv Kumar
Subject: Dahej Workshop: AutoCad Activation required

 Dear Sir,

We are using autocad 2016 at dahej workshop, which license has expired, So please do the needful to activate Autocad.

 

Regards,

Manjeet Singh

 

 




 

--
